import { Letter } from '@app/letter';

export const LETTERS: Letter[] = [
    { letter: 'A', quantity: 9, point: 1 },
    { letter: 'B', quantity: 2, point: 3 },
    { letter: 'C', quantity: 2, point: 3 },
    { letter: 'D', quantity: 3, point: 2 },
    { letter: 'E', quantity: 15, point: 1 },
    { letter: 'F', quantity: 2, point: 4 },
    { letter: 'G', quantity: 2, point: 2 },
    { letter: 'H', quantity: 2, point: 4 },
    { letter: 'I', quantity: 8, point: 1 },
    { letter: 'J', quantity: 1, point: 8 },
    { letter: 'K', quantity: 1, point: 10 },
    { letter: 'L', quantity: 5, point: 1 },
    { letter: 'M', quantity: 3, point: 2 },
    { letter: 'N', quantity: 6, point: 1 },
    { letter: 'O', quantity: 6, point: 1 },
    { letter: 'P', quantity: 2, point: 3 },
    { letter: 'Q', quantity: 1, point: 8 },
    { letter: 'R', quantity: 6, point: 1 },
    { letter: 'S', quantity: 6, point: 1 },
    { letter: 'T', quantity: 6, point: 1 },
    { letter: 'U', quantity: 6, point: 1 },
    { letter: 'V', quantity: 2, point: 4 },
    { letter: 'W', quantity: 1, point: 10 },
    { letter: 'X', quantity: 1, point: 10 },
    { letter: 'Y', quantity: 1, point: 10 },
    { letter: 'Z', quantity: 1, point: 10 },
    { letter: '*', quantity: 2, point: 0 },
];
