export enum PlacementValidity {
    HUp = 'HU',
    HDown = 'HD',
    Left = 'L',
    Right = 'R',
    HUpLeft = 'HUL',
    HUpRight = 'HUR',
    HDownLeft = 'HDL',
    HDownRight = 'HDR',
    HUpHDown = 'HUHD',
    LeftRight = 'RL',
    HUpHDownLeft = 'HUHDL',
    HUpHDownRight = 'HUHDR',
    HUpLeftRight = 'HULR',
    HDownLeftRight = 'HDLR',
    Nothing = 'N',
}
